#ddev-generated
# Remove the line above if you don't want this file to be overwritten when you run
# ddev get thunder/ddev-playwright
#
# This file comes from https://github.com/thunder/ddev-playwright
#
web_environment:
  - PW_TEST_CONNECT_WS_ENDPOINT=ws://playwright:3000
  - PLAYWRIGHT_TEST_DIR=tests/Playwright
web_extra_exposed_ports:
  - name: playwright-report
    container_port: 9323
    http_port: 9323
    https_port: 9324
  - name: playwright-ui
    container_port: 36921
    http_port: 36921
    https_port: 36922
