#!/bin/sh
#ddev-generated

cd tests/Playwright || exit 1

# If $@ contains 'test --ui' we need to add the --ui-host option to the command
if echo "$@" | grep -q "test --ui"; then
  # Add the --ui-host and --ui-port option to the command
  set -- "$@" --ui-host="0.0.0.0" --ui-port="36921"
fi

# If $@ contains 'show-report' we need to add the --host option to the command
if echo "$@" | grep -q "show-report"; then
  # Add the --host and --port option to the command
  set -- "$@" --host="0.0.0.0" --port="9324"
fi


if [ -f yarn.lock ]; then
  yarn && yarn playwright "$@"
else
  npx playwright "$@"
fi
