#!/bin/sh
#ddev-generated

cd "${PLAYWRIGHT_TEST_DIR}" || exit 1

# If $@ contains 'test --ui' we need to add the --ui-host option to the command
if echo "$@" | grep -q "test --ui"; then
  # Add the --ui-host and --ui-port option to the command
  set -- "$@" --ui-host="0.0.0.0" --ui-port="36921"
  echo "Listening on ${DDEV_PRIMARY_URL}:36922. Press Ctrl+C to quit"
fi

# If $@ contains 'show-report' we need to add the --host option to the command
if echo "$@" | grep -q "show-report"; then
  # Add the --host and --port option to the command
  set -- "$@" --host="0.0.0.0" --port="9323"
  echo "Serving HTML report at ${DDEV_PRIMARY_URL}:9324. Press Ctrl+C to quit"
fi

if echo "$@" | grep -q "codegen"; then
  echo "This command is not supported yet."
fi

if [ -f yarn.lock ]; then
  yarn && yarn playwright "$@"
else
  npx playwright "$@"
fi
